name: Daily Test
on:
  push:
  #workflow_dispatch:
  # repository_dispatch:
  #   types: [on-demand-test]
  # schedule:
  #   - cron: '10 7 * * *'

env:
  SUPERFACE_ONESDK_TOKEN: ${{ secrets.SUPERFACE_ONESDK_TOKEN }}
  SUPERFACE_REFRESH_TOKEN: ${{ secrets.SUPERFACE_REFRESH_TOKEN }}

jobs:
  cli:
    name: CLI MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install Superface CLI
        run: brew install superfaceai/cli/superface
      - run: superface --version
      - run: superface whoami

  perform_nodejs_linux:
    name: Perform Node.js Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    defaults:
      run:
        working-directory: javascript
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Perform
        run: node --experimental-wasi-unstable-preview1 --no-warnings index.mjs

  perform_nodejs_windows:
    name: Perform Node.js Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    defaults:
      run:
        working-directory: javascript
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Perform
        run: node --experimental-wasi-unstable-preview1 --no-warnings index.mjs
      
  perform_python_linux:
    name: Perform Python Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies and package locally
        run: python -m pip install -r requirements.txt
      - name: Perform
        run: python main.py

  perform_python_windows:
    name: Perform Python Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies and package locally
        run: python -m pip install -r requirements.txt
      - name: Perform
        run: python main.py