name: Daily Test
on:
  push:
  #workflow_dispatch:
  # repository_dispatch:
  #   types: [on-demand-test]
  # schedule:
  #   - cron: '10 7 * * *'

env:
  SUPERFACE_ONESDK_TOKEN: ${{ secrets.SUPERFACE_ONESDK_TOKEN }}

jobs:
  nodejs_linux:
    name: Node.js Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    defaults:
      run:
        working-directory: javascript
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Perform
        run: node --experimental-wasi-unstable-preview1 --no-warnings index.mjs

  python_linux:
    name: Python Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies and package locally
        run: python -m pip install -r requirements.txt
      - name: Perform
        run: python main.py

  nodejs_windows:
    name: Node.js Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    defaults:
      run:
        working-directory: javascript
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Perform
        run: node --experimental-wasi-unstable-preview1 --no-warnings index.mjs
      